name: Build Documentation

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: '--cfg docsrs -D warnings'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
    - name: Build Documentation
      run: cargo doc --all-features
